/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import javax.swing.text.MaskFormatter;
import java.text.ParseException;
import java.util.InputMismatchException;
import java.util.Scanner;

public class App {

    public static int pegarNumero(String mensagem) throws InputMismatchException, ParseException { //encaminha a exc do Scanner ->Tipo invalido de escrita

        //nao foi
        do{
            Scanner teclado = new Scanner(System.in);
            try{
                MaskFormatter mask = new MaskFormatter("(##)");
                System.out.printf(mensagem);
                int numero = teclado.nextInt();
                return numero;
            }catch (InputMismatchException e){
                System.err.println("apenas numeros");
                teclado.nextLine();
            }
            finally {
                System.out.println("sempre passa aq");
                teclado.close();
            }
        }while(true);
    }


    public static void main(String[] args) throws ParseException { //throws pro mask


        pegarNumero("digite valor");


        //     int[] vetor = new int[10];
//
//     int a = 10;
//
//
//     try{
////        System.out.printf("Entre com o numero: ");
////        int numero = teclado.nextInt();                 //problema
////        System.out.println("entre com a posicao: ");
////        int posicao = teclado.nextInt();                //problema
//
//         int numero = pegarNumero("Entre com número: ");
//         int posicao = pegarNumero("Entre com a posição: ");
//         int n = pegarNumero("oi");  //o PegarNumero joga pra main cuidar ent tem q estar aq dentro p tratar, se por o throw no main ele joga pra maquina virtual (q mostra o erro)
//
//         vetor[posicao]=numero;                          //problema
//
//     }catch (InputMismatchException e){                  //excep generica ->Exception e
//         System.err.println("Somente números por favor");
//     }catch (ArrayIndexOutOfBoundsException e){
//         System.err.println("Fora do limite!");
//     } catch (Exception e) {
//         System.err.println("Comportamento inesperado");
//     }





    }
}
